version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - STAGE=dev
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3